version: '3.9'

services:

  api-service:
    container_name: api-service
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      API_TITLE: API DOCS DEV
    ports:
      - '8080:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge
